### ISSUE TITLE
Security warning due to Pillow

### ISSUE THREAD

**Issue by DaBeIDS** [os-climate/corporate_data_extraction#15]
https://github.com/os-climate/corporate_data_extraction/security/dependabot/19

It has to be checked if we can easily upgrade to the suggested Pillow version.

**Comment by DaBeIDS** [comment]
Additional note: A lot of the security warnings are due to Pillow.

https://github.com/os-climate/corporate_data_extraction/security/dependabot

**Comment by ModeSevenIndustrialSolutions** [comment]
Sorted today.
