### ISSUE TITLE
Boto3 needs Python >= 3.8 from december on 

### ISSUE THREAD

**Issue by DaBeIDS** [os-climate/corporate_data_extraction#20]
In the extraction docker i got the following warning:

![image](https://github.com/os-climate/corporate_data_extraction/assets/90916810/15ef1654-2352-48a9-bc47-682fb763ddd2)

This has to be handled until then.

**Comment by HeatherAck** [comment]
python upgrade is captured in epic:  https://github.com/os-climate/os_c_data_commons/issues/234
